module.exports = {
  "tracks": [
    { name: 'Sound Of A Woman', id: '0c6xIDDpzE81m2q797ordA'},
    { name: 'Del Mar', id: '5cpJFiNwYyWwFLH0V6B3N8'},
    { name: 'Yellow', id: '3AJwUDP919kvQ9QcozQPxg'},
    { name: 'Butter', id: '2bgTY4UwhfBYhGT4HUYStN'},
    { name: 'Stardust', id: '45E6bRQfFgG71K6A0uwPsW'}
  ],
  "artists": [
    { name:'Sia', id: '5WUlDfRSoLAfcVSX1WnrxN'},
    { name:'ColdPlay', id: '4gzpq5DPGxSnKTe4SA8HAU'},
    { name:'BTS', id: '3Nrfpe0tUJi4K4DXYWgMUX'},
    { name:'Adele', id: '4dpARuHxo51G3z768sgnrY'},
    { name:'Alex Lustig', id: '5oLxJrktO7kOEJANS6nkZB'}
  ],
  "genres": [
    "acoustic",
    "afrobeat",
    "alt-rock",
    "alternative",
    "ambient",
    "anime",
    "black-metal",
    "bluegrass",
    "blues",
    "bossanova",
    "brazil",
    "breakbeat",
    "british",
    "cantopop",
    "chicago-house",
    "children",
    "chill",
    "classical",
    "club",
    "comedy",
    "country",
    "dance",
    "dancehall",
    "death-metal",
    "deep-house",
    "detroit-techno",
    "disco",
    "disney",
    "drum-and-bass",
    "dub",
    "dubstep",
    "edm",
    "electro",
    "electronic",
    "emo",
    "folk",
    "forro",
    "french",
    "funk",
    "garage",
    "german",
    "gospel",
    "goth",
    "grindcore",
    "groove",
    "grunge",
    "guitar",
    "happy",
    "hard-rock",
    "hardcore",
    "hardstyle",
    "heavy-metal",
    "hip-hop",
    "holidays",
    "honky-tonk",
    "house",
    "idm",
    "indian",
    "indie",
    "indie-pop",
    "industrial",
    "iranian",
    "j-dance",
    "j-idol",
    "j-pop",
    "j-rock",
    "jazz",
    "k-pop",
    "kids",
    "latin",
    "latino",
    "malay",
    "mandopop",
    "metal",
    "metal-misc",
    "metalcore",
    "minimal-techno",
    "movies",
    "mpb",
    "new-age",
    "new-release",
    "opera",
    "pagode",
    "party",
    "philippines-opm",
    "piano",
    "pop",
    "pop-film",
    "post-dubstep",
    "power-pop",
    "progressive-house",
    "psych-rock",
    "punk",
    "punk-rock",
    "r-n-b",
    "rainy-day",
    "reggae",
    "reggaeton",
    "road-trip",
    "rock",
    "rock-n-roll",
    "rockabilly",
    "romance",
    "sad",
    "salsa",
    "samba",
    "sertanejo",
    "show-tunes",
    "singer-songwriter",
    "ska",
    "sleep",
    "songwriter",
    "soul",
    "soundtracks",
    "spanish",
    "study",
    "summer",
    "swedish",
    "synth-pop",
    "tango",
    "techno",
    "trance",
    "trip-hop",
    "turkish",
    "work-out",
    "world-music"
  ]
}